### PR TITLE
Implement fixer

### PR DESCRIPTION
**Pull request by firelizzard18**
Updates the analyzer to support automatic fixes for golangci-lint.

Updates #2.

### CODE REVIEW

**Comment by firelizzard18** [comment]
@denis-tingaikin

**Comment by denis-tingaikin** [comment]
@firelizzard18 Woot! Looks good. Let me test it a bit.

**Review by denis-tingaikin — APPROVED** [review]

**Comment by denis-tingaikin** [comment]
As I can see we have only one problem with a test.

It's related to oudated input for the expected value here https://github.com/denis-tingaikin/go-header/blob/main/analyzer_test.go#L57

that we can fix with something like this:
```diff
---require.Nil(t, a.Analyze(header(`A 2000-2022 B`)))
+++require.Nil(t, a.Analyze(header(fmt.Sprintf("A 2000-%v B", time.Now().Year()))))

```

**Comment by firelizzard18** [comment]
@denis-tingaikin I applied the fix for the test

**Comment by denis-tingaikin** [comment]
@firelizzard18 Great work! Merging..

**Comment by millermatt** [comment]
Can someone explain how to use this? I have go-header@0.5.0 and it doesn't accept a `-fix` param on the command line.

**Comment by firelizzard18** [comment]
I built this to integrate with golangci-lint. I did not add a flag to the goheader binary.

**Comment by millermatt** [comment]
@firelizzard18 Great! I'm using golangci-lint.

In my project root I have `.golangci.yaml` with this content:
```yaml
linters:
  enable:
    - goheader

linters-settings:
  goheader:
    template-path: configs/goheader.tmpl
```

I run golangci-linter like this and it finds my file with a non-forming header:

```
docker run --rm -t -v $(pwd):/app -v ~/.cache/golangci-lint/v1.61.0:/root/.cache -w /app golangci/golangci-lint:v1.61.0 golangci-lint run
cmd/foo/main.go:1:1: Actual: foo
Expected:/* (goheader)
/*

foo

*/
make: *** [Makefile:39: lint] Error 1
```

I've tried adding `fix: true` like this, but it does nothing:

```yaml
linters-settings:
  goheader:
    template-path: configs/goheader.tmpl
    fix: true
```

How do I eneable fixing?

**Comment by millermatt** [comment]
Nevermind - I found the setting:

```
issues:
  fix: true
```

Aplogies, I'm just starting to use the tooling.

**Pull request merged**
